# 公有仓库
#source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'
## 私有仓库
source 'http://git.lianheng.com.cn/iOS/LianHengSpecs.git'

use_frameworks!

target 'CRProjectInfo_Example' do
  pod 'CRProjectInfo', :path => '../'

  target 'CRProjectInfo_Tests' do
    inherit! :search_paths

    
  end
end
